[package]
name = "lumos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
page_size = "0.5.0"
tokio = {version = "1", features = ["full"]}
